--- mcphub._native.edit.ui_backend — `drive_file` callback driven by mcphub's `EditUI`.
---
--- ## Why this file lives here, not under `lua/nvu/edit/`
---
--- The pure engine in `lua/nvu/edit/` deliberately does not import anything
--- from mcphub. This file is the bridge: it implements the `drive_file`
--- shape documented in `nvu.edit.applier.apply_plan` against mcphub's
--- `EditUI`. Any caller wanting a non-mcphub backend (CLI batch mode, a
--- synthetic test driver, etc.) can write a sibling that conforms to the
--- same call contract.
---
--- ## What we reuse from mcphub
---
--- Only `EditUI` itself — not `EditSession`, `DiffParser`, or
--- `BlockLocator`. Those comprise the SEARCH/REPLACE protocol layer we're
--- replacing. `EditUI` is the reusable piece: open file → apply changes →
--- per-hunk review (when interactive) → write. We feed it pre-resolved
--- `LocatedBlock`s constructed from the applier's `Block[]` request.
---
--- See the spelunking notes in `/memories/parked-sessions/nvu-edit-tool.md`
--- for the load-bearing observations about `EditUI`'s shape: `interactive`
--- propagation, `completed_hunks` snapshot timing, `cleanup()` nils state,
--- `get_summary` is async, `_apply_all_changes` sorts ascending internally.
---
--- @module "mcphub._native.edit.ui_backend"

local M = {}

--- Build the `LocatedBlock`-shaped table `EditUI` expects, from one of the
--- applier's `Block`s. `EditUI` needs:
---
---   * `block_id`               — scopes the per-hunk IDs generated by
---                                `_generate_hunk_blocks`.
---   * `search_content` / lines — used by `_generate_block_summary` for the
---                                LLM-facing report. Not load-bearing for
---                                the apply path.
---   * `replace_content` / lines — what gets inserted by `_apply_all_changes`.
---   * `location_result`        — `{ found = true, start_line, end_line,
---                                found_lines, ... }`. `_apply_all_changes`
---                                reads `start_line` / `end_line`;
---                                `_generate_hunk_blocks` reads `found_lines`.
---
--- The other `BlockLocationResult` fields are informational (the SEARCH/
--- REPLACE locator emits them for fuzzy-match feedback). We provide
--- harmless defaults so any field reads don't crash on nil.
---
--- @param bufnr      integer
--- @param block      nvu.edit.applier.Block
--- @return table     LocatedBlock-shaped table (mcphub's types.lua).
local function to_located_block(bufnr, block)
    local start_line, end_line = block.range.start_line, block.range.end_line

    -- Read the lines currently in this range. For a zero-width insertion
    -- (`end_line < start_line`), `nvim_buf_get_lines(s-1, e, ...)` with
    -- `s-1 == e` returns the empty list, which is what we want.
    local found_lines = (end_line < start_line)
        and {}
        or vim.api.nvim_buf_get_lines(bufnr, start_line - 1, end_line, false)

    local search_text   = table.concat(found_lines, '\n')
    local replace_lines = block.replace_lines
    local replace_text  = table.concat(replace_lines, '\n')

    return {
        block_id        = block.block_id,
        search_content  = search_text,
        search_lines    = found_lines,
        replace_content = replace_text,
        replace_lines   = replace_lines,
        location_result = {
            found              = true,
            start_line         = start_line,
            end_line           = end_line,
            found_lines        = found_lines,
            -- Informational defaults — EditUI's summary code reads these
            -- but treats them as additive; nil would be fine in practice
            -- but explicit defaults keep the contract obvious.
            overall_score      = 1.0,
            overall_match_type = 'exact',
            confidence         = 100,
            found_content      = search_text,
            line_details       = {},
            search_metadata    = {
                method            = 'exact_scan',
                iterations        = 0,
                search_strategy   = 'auto',
                search_bounds     = { start_line, end_line < start_line and start_line or end_line },
                early_termination = false,
            },
        },
    }
end

--- Walk `EditUI.state.completed_hunks` and aggregate hunk-level statuses up
--- to the block level (`per_block[block_id]`). `EditUI` generates hunk IDs
--- of the form `<block_id>_hunk_<N>`, so we scan by prefix.
---
--- Aggregation rule:
---   * any hunk rejected and any hunk accepted → 'partial'
---   * any hunk rejected, none accepted        → 'rejected'
---   * no hunks (block produced no diff)       → absent (treated as accepted by classify_outcome)
---   * all hunks accepted/skipped              → 'accepted'
---
--- `EditUI` uses status `'skipped'` for hunks that couldn't be navigated
--- (e.g. content already matched). For our purposes that's a successful
--- no-op — group it with `'accepted'`.
---
--- @param completed_hunks table<string, string>
--- @param block_ids       string[]
--- @return table<string, string>
local function aggregate_per_block(completed_hunks, block_ids)
    local per_block = {}
    for _, block_id in ipairs(block_ids) do
        local prefix = block_id .. '_'
        local any_rejected, any_accepted = false, false
        local n = 0
        for hunk_id, status in pairs(completed_hunks) do
            if hunk_id:sub(1, #prefix) == prefix then
                n = n + 1
                if status == 'rejected' then
                    any_rejected = true
                elseif status == 'accepted' or status == 'skipped' then
                    any_accepted = true
                end
            end
        end
        if n == 0 then
            -- absent: classify_outcome treats this as accepted on a completed
            -- file and as cancelled on a cancelled file. Don't set anything.
        elseif any_rejected and any_accepted then
            per_block[block_id] = 'partial'
        elseif any_rejected then
            per_block[block_id] = 'rejected'
        else
            per_block[block_id] = 'accepted'
        end
    end
    return per_block
end

--- Drive one file's edits through `EditUI`. Implements the `drive_file`
--- contract from `nvu.edit.applier.apply_plan`.
---
--- @param request  nvu.edit.applier.FileRequest
--- @param file_cb  fun(outcome: nvu.edit.applier.FileOutcome)
function M.drive_file(request, file_cb)
    local EditUI = require'mcphub.native.neovim.files.edit_file.edit_ui'

    -- Convert applier blocks → EditUI LocatedBlocks. Also keep the parallel
    -- block_id list for outcome aggregation.
    local located_blocks, block_ids = {}, {}
    for _, b in ipairs(request.blocks) do
        located_blocks[#located_blocks + 1] = to_located_block(request.bufnr, b)
        block_ids[#block_ids + 1] = b.block_id
    end

    -- Guard against the degenerate "no blocks" case. The applier shouldn't
    -- send us this (planner emits at least one located op per included
    -- file), but a defensive return keeps the contract well-defined.
    if #located_blocks == 0 then
        return file_cb{ status = 'no_changes', per_block = {} }
    end

    -- Origin window for "return-to-origin on complete". The current window
    -- is fine: `EditUI.open_file_in_editor` filters by `buftype == ""` when
    -- picking a target split, so the CodeCompanion chat (buftype = "acwrite")
    -- is structurally excluded — see spelunking notes.
    local origin_winnr = vim.api.nvim_get_current_win()

    -- `EditUI.new` deep-merges over its own DEFAULT_CONFIG, so an empty table
    -- is the correct way to say "use all defaults". mcphub's UIConfig
    -- annotation marks every field as required, which is wrong for this
    -- entry point — silence the diagnostic.
    ---@diagnostic disable-next-line: missing-fields
    local ui = EditUI.new({})

    -- Both completion paths share the same epilogue: snapshot state, fetch
    -- summary (async), cleanup, hand outcome to file_cb. We must read
    -- `ui.state.completed_hunks` BEFORE `ui:cleanup()` because cleanup nils
    -- the state table.
    local function finalise(status, cancel_reason)
        local completed_hunks = vim.deepcopy(ui.state and ui.state.completed_hunks or {})
        local per_block = aggregate_per_block(completed_hunks, block_ids)

        -- `get_summary` is async (it may wait for diagnostics). We disable
        -- diagnostic plumbing here — that's a M4 concern. The summary is
        -- still informative without it.
        local summary_config = {
            include_session_summary = true,
            include_final_diff      = false,
            send_diagnostics        = false,
            wait_for_diagnostics    = 0,
        }
        ui:get_summary(summary_config, function(summary_text)
            ui:cleanup()
            file_cb{
                status        = status,
                cancel_reason = cancel_reason,
                per_block     = per_block,
                ui_summary    = summary_text ~= '' and summary_text or nil,
            }
        end)
    end

    ui:start_interactive_editing{
        interactive              = request.interactive ~= false,
        is_replacing_entire_file = false,
        origin_winnr             = origin_winnr,
        file_path                = request.file_path,
        located_blocks           = located_blocks,
        original_content         = request.original_content,
        on_complete = function() finalise('completed', nil) end,
        on_cancel   = function(reason) finalise('cancelled', reason) end,
    }
end

return M
